services:
  ESI-Interface:
    build:
      context: ./ESI-Interface
      dockerfile: Dockerfile
    container_name: ESI-Interface
    image: skyemeadows/eve-esi-interface:latest
    restart: unless-stopped
    env_file: 
      - .env
    volumes:
      - /home/skye/programs/Shared-Content:/Shared-Content

  The-Market-Hand:
    build:
      context: ./The-Market-Hand
      dockerfile: Dockerfile
    container_name: The-Market-Hand
    image: skyemeadows/eve-the-market-hand:latest
    restart: unless-stopped
    env_file: 
      - .env
    volumes:
      - /home/skye/programs/Shared-Content:/Shared-Content

  Anomaly-Evaluator:
    build:
      context: ./Anomaly-Evaluator
      dockerfile: Dockerfile
    container_name: Anomaly-Evaluator
    image: skyemeadows/eve-anomaly-evaluator:latest
    restart: unless-stopped
    env_file: 
      - .env
    volumes:
      - /home/skye/programs/Shared-Content:/Shared-Content
